### ISSUE TITLE
Styling tour-step-template

### ISSUE THREAD

**Issue by zbrugman** [isaacplmann/ng2-tour#15]
Hey, great work! I was wondering if there was an easy way to control the HTML of the tour-step-template. I see the template is included in `tour-step-template.component.ts` but was curious how I could alter some of the HTML and CSS classes contained there without overwriting with a bunch of messy CSS.

Thanks!

**Comment by isaacplmann** [comment]
Probably the best way is to write your own UI plugin module using `TourModule`, just like `TourNgBootstrapModule` does.   Just look at the [ngbootstrap plugin](https://github.com/isaacplmann/ng2-tour/tree/master/src/lib/plugin/ng-bootstrap) or the [console plugin](https://github.com/isaacplmann/ng2-tour/tree/master/src/lib/plugin/console) for examples of how to do that.  You can use any UI library you want that way and have complete control over what is displayed.

**Comment by zbrugman** [comment]
Awesome, I'll give that a try - thank you for the quick reply!

**Comment by isaacplmann** [comment]
Also, if you're able to do it, it would be great if you could share your plugin with other people - either as a PR to this repo or in a separate repo that depends on this one.

**Comment by zbrugman** [comment]
Right on, will do

**Comment by isaacplmann** [comment]
Thanks for submitting a PR (#16).  It looks like you were able to solve your issue with it.

**Comment by isaacplmann** [comment]
FYI, I've added the ability to specify your own template for the tour steps with `ngx-tour-ng-bootstrap@1.x` and `ngx-tour-md-menu@1.x`.  This means you could stop maintaining your fork, if you want.

**Comment by zbrugman** [comment]
👍  That's great! Thank you for the heads up.

**Comment by kahboom** [comment]
To integrate with ngx-boostrap instead of ng-bootstrap or Angular Material, is it recommended I create a plugin the same way?

**Comment by isaacplmann** [comment]
@kahboom Yes, that's what I would recommend.  Feel free to open another issue if you want to talk through how you might go about doing that.  I'd be happy to help.
