### ISSUE TITLE
Uncaught (in promise): TypeError: scrollIntoViewIfNeeded is not a function 

### ISSUE THREAD

**Issue by beuntje** [isaacplmann/ng2-tour#18]
I'm getting following error, as well on local project where I'm implementing ng2-tour, as in demo-project forked from github... 

```
EXCEPTION: Uncaught (in promise): TypeError: scrollIntoViewIfNeeded is not a function
TypeError: scrollIntoViewIfNeeded is not a function
    at TourAnchorNgBootstrapDirective.showTourStep
```
(scroll-into-view-if-needed version 1.1.0)

**Comment by isaacplmann** [comment]
Should be fixed in version 0.1.6 via PR #12 .  Let me know if its still broken.

**Comment by beuntje** [comment]
issue seems to be fixed. Thanks a lot

(off topic / fyi: on https://isaacplmann.github.io/ng2-tour/ there's a new exception thrown. On my local machine I don't have that problem)

**Comment by isaacplmann** [comment]
Thanks for the heads up.  I’ll look into that.
